### ISSUE TITLE
no uvfits key for integration time

### ISSUE THREAD

**Issue by d3v-null** [MWATelescope/Marlu#13]
We don't write the `INTTIM` / `INTTIME` key, because Cotter never did.
This is an issue, because if you're writing a uvfits file with only 1 timestep, then it's impossible to determine the integration time.

**Comment by d3v-null** [comment]
pyuvdata does this with the `INTTIM` group parameter: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/blob/11e7129af5b105f066e505abb3383c41af3d6bcf/pyuvdata/uvdata/uvfits.py#L1141

**Comment by cjordan** [comment]
`INTTIM` is provided as of 8ae0d5c016faadf94a5d06b35bc8e00d64f391b0
