### ISSUE TITLE
using indicatif 0.17.4 or above causes a test to fail sometimes

### ISSUE THREAD

**Issue by d3v-null** [MWATelescope/Marlu#25]
by editing cargo toml, I experimented with a few versions of indicatif, and I found that versions 0.17.4 and 0.17.5 had some issue that caused this test to fail about 50% of the time.

```bash
cargo test io::uvfits::tests::avg_center_frequencies
```

This didn't happen on 0.17.{1..3} 

Here's a stack trace.

![Screen Shot 2023-07-14 at 4 06 05 pm](https://github.com/MWATelescope/Marlu/assets/2578076/9665b8b4-f59f-436b-96df-c3051515e550)

**Comment by cjordan** [comment]
No longer an issue as `Marlu` no longer uses `indicatif`
